time_limit_sec_force: 300
solver_name: "refiner-4"
solver_options:
  # common
  - "--checkpoints-duration"
  - "1"
  - "--pibt-num"
  - "1"
  - "--random-insert-prob1"
  - "0.001"
  - "--random-insert-prob2"
  - "0.0"
  - "--no-scatter"
  # tested parameters
  - "--refiner-num"
  - "4"
