solver_name: "lacam3-no-scatter"
solver_options:
  # common
  - "--checkpoints-duration"
  - "1"
  - "--pibt-num"
  - "10"
  - "--random-insert-prob1"
  - "0.001"
  - "--random-insert-prob2"
  - "0.01"
  - "--no-scatter"
  - "--refiner-num"
  - "1"
  - "--recursive-rate"
  - "0"
