solver_name: "lacam3-no-random"
solver_options:
  # common
  - "--checkpoints-duration"
  - "1"
  - "--pibt-num"
  - "10"
  - "--random-insert-prob1"
  - "0.001"
  - "--random-insert-prob2"
  - "0.0"
  - "--scatter-margin"
  - "10"
  - "--refiner-num"
  - "1"
  - "--recursive-rate"
  - "0"
